### ISSUE TITLE
01 Distribution map

### ISSUE THREAD

**Issue by klatifiana** [klatifiana/kingfisher-project#1]
## Task-1: Distribution of the blue-banded kingfisher in Petungkriyono
*Timeline: The latest week of November 2022*  
*In progress* ![](https://geps.dev/progress/90)  

### Objective
- Layout map of points distribution --> static layout

### Layers
- [x] Sighting coordinates: Lon-Lat --> received Nov 8, 2022 (*.xlsx)
- [x] Track survey, incl. points survey and presence --> received Nov 10, 2022 (*.kmz) --> main data
- [ ] River shp: BIG 25K 2017
- [x] Watershed shp: MoEF 250K year?
- [x] Border scope: Landscape of Mt. Dieng and Slamet --> received Nov 8, 2022 (*.kmz)
- [x] Administrative border BIG 2017
- [x] Basemap: Planet visual monthly monitoring - June 2022

### Next steps
- [x] Refine the coordinates to appropriate spatial format
- [ ] Confirm the maps

### Cartography map detail
|Info|Remark|
|-----|------|
|Title| Javan Blue-banded Kingfisher Field Survey Coverage in Five Main Rivers of Sengkarang Watershed, Central Java, Indonesia |
|Data source| Geospatial Information Agency, 2017; Watershed Border by Ministry of Environment and Forestry; Fieldwork in Apr-Jun 2022; Planet Imagery Basemap June 2022|
|CRS| WGS 84 / Pseudo-Mercator - EPSG 32749 |
|Logo| No |
|Size| A4 - Portrait|

**Comment by klatifiana** [comment]
beberapa detil yg perlu perbaikan

1. Beberapa titik surveinya aku salah input. Jadi:
- titik 7-4 Kumenyep dihapus
- titik 13-3 dan 13-4 Sengkarang dihapus, yg disurvei ternyata titik 14-4
- titik survei berperahu start dari 4-1. Titik 4-2, 4-3, dan 4-4 dihapus

2. Beberapa titik perjumpaan raja-udang kalung-biru yang di Welo itu dari kegiatan pra-survei. Dua yang pertama perlu dimasukkan ke peta laporan, tapi perlu warna berbeda:
- 5-5
- 6-4
Yg ini dari pengamatan sendiri sebelum project. Nanti bisa buat data sekunder modeling-nya:
- 8-3
- 8-4
- 9-3

3. Peta yg di-inset perlu dikasih garis yg lebih tegas/tebal
